### ISSUE TITLE
modV does not work in Linux Mint 20.1

### ISSUE THREAD

**Issue by defensem3ch** [vcync/modV#553]
**Operating system and application version**
 - OS: Linux Mint 20.1
 - Version 3.11.0

**Describe the bug**
Running either the AppImage or snap package of version 3.11.0 only opens one window that shows File, Edit, Project, View, Window, Help. The entire window is white and does not look like the first windows shown here: https://github.com/vcync/modV-Workshop#modv-setup

**To Reproduce**
Run `./modV-3.11.0.AppImage` or install the snap package and run `modv`

**Expected behavior**
Two windows should open: The main window and the output window.

**Screenshots**
![modV_393](https://user-images.githubusercontent.com/72157321/108271463-d6c3cf80-713e-11eb-8f1b-2b440168cdac.png)

**Additional context**
Console log:
```
❯ ./modV-3.11.0.AppImage
Checking for update
(node:587101) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:587101) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
[4:37:05 PM]: Added ReadHandler for image
[4:37:05 PM]: Added ReadHandler for palette
[4:37:05 PM]: Added ReadHandler for preset
[4:37:05 PM]: Added ReadHandler for module
[4:37:05 PM]: Added SaveHandler for preset
(node:587101) UnhandledPromiseRejectionWarning: TypeError: n.systemPreferences.getMediaAccessStatus is not a function
    at /tmp/.mount_modV-3Xmd841/resources/app.asar/background.js:415:140853
    at Object.create (/tmp/.mount_modV-3Xmd841/resources/app.asar/background.js:415:141506)
    at ce (/tmp/.mount_modV-3Xmd841/resources/app.asar/background.js:415:145010)
    at App.<anonymous> (/tmp/.mount_modV-3Xmd841/resources/app.asar/background.js:415:146128)
    at App.emit (events.js:315:20)
(node:587101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:587101) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Update for version 3.11.0 is not available (latest version: 3.11.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```

**Comment by 2xAA** [comment]
@defensem3ch thanks for documenting the issue.

Looks like an OS check for Linux in `src/background.js` needs to take place in the function on line 22.
 
@TimPietrusky I still have no access to a Linux machine and I currently don't have the space on any of my machines to create a partition.

Can we address this in our weekly triage session?

**Comment by TimPietrusky** [comment]
@defensem3ch we fixed it with the latest release, can you please check again?

**Comment by defensem3ch** [comment]
looks like result is the same. Console output:
```
❯ ./modV-3.12.0.AppImage
Checking for update
(node:139538) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:139538) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
[5:10:55 PM]: Added ReadHandler for image
[5:10:55 PM]: Added ReadHandler for palette
[5:10:55 PM]: Added ReadHandler for preset
[5:10:55 PM]: Added ReadHandler for module
[5:10:55 PM]: Added SaveHandler for preset
Update for version 3.12.0 is not available (latest version: 3.12.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```

**Comment by 2xAA** [comment]
@defensem3ch How do you mean the result is the same, still a totally blank screen?

**Comment by defensem3ch** [comment]
@2xAA Correct, the window looks the same as in the previous screenshot

**Comment by defensem3ch** [comment]
@TimPietrusky @2xAA I tested the snap package and am still getting the same window as in the original screenshot. Console output:
```
❯ modv
Gtk-Message: 17:34:12.384: Failed to load module "xapp-gtk3-module"
SNAP env is defined, updater is disabled
(node:98129) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:98129) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
[5:34:13 PM]: Added ReadHandler for image
[5:34:13 PM]: Added ReadHandler for palette
[5:34:13 PM]: Added ReadHandler for preset
[5:34:13 PM]: Added ReadHandler for module
[5:34:13 PM]: Added SaveHandler for preset
```

**Comment by 2xAA** [comment]
@defensem3ch Thanks for testing.

My Linux laptop fatally broke just this morning so I'll need to get that repaired before I can look into this properly.

Though a build with the fixes worked yesterday with Ubuntu 20, so I'm not sure what the issue is now.

Can you open the dev console in modV using Ctrl+Shift+I and paste the output here?

**Comment by defensem3ch** [comment]
@2xAA oh no! Let me know if you need any further info from me in the meantime. Here's the output of the dev console:
```
electron/js2c/asar_bundle.js:5 Uncaught Error: libndi.so.4: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5)
    at Module.load (internal/modules/cjs/loader.js:992)
    at Module._load (internal/modules/cjs/loader.js:885)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Module.require (internal/modules/cjs/loader.js:1032)
    at require (internal/modules/cjs/helpers.js:72)
    at bindings (/snap/modv/x1/resources/app.asar/node_modules/bindings/bindings.js:112)
    at Object.<anonymous> (/snap/modv/x1/resources/app.asar/node_modules/grandiose/index.js:18)
DevTools failed to load SourceMap: Could not parse content for app://./js/index.15aa9c34.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for app://./js/chunk-vendors.8b979df2.js.map: Unexpected end of JSON input
```

**Comment by 2xAA** [comment]
Hey @defensem3ch!

We've identified this latest error as libndi missing from your machine.
It is mentioned in the README here: https://github.com/vcync/modV#ubuntudebian (we recognise now that this information is in the incorrect place, we'll fix that up) 

Once installed modV should work fine for you, even the latest release.

#564 should be merged soon, that adds a dialog to display this error gracefully and the user is directed to the README.

**Comment by defensem3ch** [comment]
@2xAA I thought that was the case when I posted the log too! So I went ahead and installed that package (screenshot attached). Is there a chance it's just not being found in the right place? I'm still getting the exact same window as shown in the OP (and the same error in the console as the previous comment).
![Selection_487](https://user-images.githubusercontent.com/72157321/110559121-a6ee6300-8111-11eb-9977-8a80b4f4f206.png)

**Comment by 2xAA** [comment]
Hey @defensem3ch,

It should be looking in the right place. There are a range of places the NDI implementation will look for the library file.

We've had success with Ubuntu 16 and 20 but just to make sure, I've just downloaded Linux Mint 20.1 and tested the steps myself.

modV (3.12.1) run without libndi (4.5.1-1) produces the error message with "Error: libndi.so.4:".

Installing libndi and trying modV again works without a problem.

Could you please check the modV version?
Maybe try removing libndi and installing again.

**Comment by defensem3ch** [comment]
@2xAA OK good news! I reinstalled libndi and the AppImage works. However even after reinstalling the snap package,it still gives the libdni error. edit: this is with latest release 3.12.0

**Comment by 2xAA** [comment]
_it's bugs all the way down!_ 🙃 

Thanks @defensem3ch for your patience and testing.

Looks like we're building the snap package with "strict confinement" which is preventing the library file being accessed.
https://snapcraft.io/docs/snap-confinement

We'll need to build as "classic" or somehow include the library file in with the build, which means forking another dependancy.

I think for now we should just change the build step and build a "classic" snap package.
Users will need to use the `--classic` flag when installing the package.
https://www.electron.build/configuration/snap

cc @TimPietrusky

**Comment by 2xAA** [comment]
Alright, finally I think we've got to the end of this rabbit-hole 😅 

Just built modV on Linux Mint with the snap confinement as "classic" and it's definitely working.
Used `snap install ./modv_amd64.snap --dangerous --classic` to install the package.

We'll need to wait for a new modV build. Any version above 3.12.1 will have the updated snap package.

Just waiting for https://github.com/vcync/modV/pull/564 to be merged before triggering a new build.

**Comment by defensem3ch** [comment]
Brilliant thanks so much!

**Comment by TimPietrusky** [comment]
@2xAA what a nice set of flags :D I really would love to install something classic, which is dangerous at the same time. So something new for our README?

**Comment by 2xAA** [comment]
@TimPietrusky Maybe! VSCode is a classic snap package, so if it's good enough for Microsoft? 🤷‍♂️
