### PR TITLE
fix(linux): Don't check permissions when on a linux based system.

### LINKED ISSUE #553: modV does not work in Linux Mint 20.1
**Operating system and application version**
 - OS: Linux Mint 20.1
 - Version 3.11.0

**Describe the bug**
Running either the AppImage or snap package of version 3.11.0 only opens one window that shows File, Edit, Project, View, Window, Help. The entire window is white and does not look like the first windows shown here: https://github.com/vcync/modV-Workshop#modv-setup

**To Reproduce**
Run `./modV-3.11.0.AppImage` or install the snap package and run `modv`

**Expected behavior**
Two windows should open: The main window and the output window.

**Screenshots**
modV_393

**Additional context**
Console log:
```
❯ ./modV-3.11.0.AppImage
Checking for update
(node:587101) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:587101) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
[4:37:05 PM]: Added ReadHandler for image
[4:37:05 PM]: Added ReadHandler for palette
[4:37:05 PM]: Added ReadHandler for preset
[4:37:05 PM]: Added ReadHandler for module
[4:37:05 PM]: Added SaveHandler for preset
(node:587101) UnhandledPromiseRejectionWarning: TypeError: n.systemPreferences.getMediaAccessStatus is not a function
    at /tmp/.mount_modV-3Xmd841/resources/app.asar/background.js:415:140853
    at Object.create (/tmp/.mount_modV-3Xmd841/resources/app.asar/background.js:415:141506)
    at ce (/tmp/.mount_modV-3Xmd841/resources/app.asar/background.js:415:145010)
    at App.<anonymous> (/tmp/.mount_modV-3Xmd841/resources/app.asar/background.js:415:146128)
    at App.emit (events.js:315:20)
(node:587101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:587101) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Update for version 3.11.0 is not available (latest version: 3.11.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```

### PR DESCRIPTION
**Pull request by TimPietrusky**
fix #553

### CODE REVIEW

**Review by 2xAA — APPROVED** [review]
LGTM!
